### ISSUE TITLE
How to mount workshop addons manually on a dedicated server????????

### ISSUE THREAD

**Issue by nieumiemwymyslicnazwy** [Balimbanana/SM-Synergy#20]
I'm using synergy twitch beta branch dedicated server and i want to install workshop addons on it and client-side addon download

**Comment by Balimbanana** [comment]
I don't believe there is a client-side download system in place for any branch of Synergy currently. The Twitch and development branches do have a `cfg\workshop_srv.cfg` which you can put item ID's one per line and the server will download/update them on start up. Otherwise, the way to download addons for dedicated server is by SteamCMD with
`workshop_download_item 17520 <WorkshopID>`
Then if you don't have it linked by script you would have to move it manually from `steamapps\workshop\17520\<WorkshopID>` to `steamapps\common\syntwitch\synergy\custom`

**Comment by Balimbanana** [comment]
It sort of works, but there is no reason to use it. It will not affect the workshop system or forwarding, pretty much the only thing it will do in Synergy is if you favorite the server, it will still show the server in favorites if the IP changes.

**Comment by nieumiemwymyslicnazwy** [comment]
Ok, thanks for clearing it for me

**Comment by nieumiemwymyslicnazwy** [comment]
n

**Comment by nieumiemwymyslicnazwy** [comment]
I don't know why but +sv_setsteamaccount makes server with workshop addons load very slow
